In [1]:
!pip install pandas
!pip install openpyxl

import pandas as pd
import openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\12401390\appdata\roaming\python\python312\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\12401390\appdata\roaming\python\python312\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\program files\python312\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata in c:\users\12401390\appdata\roaming\python\python312\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in c:\program files\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.3.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\12401390\appdata\roaming\python\python312\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\12401390\appdata\roaming\python\python312\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 23.3.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
caminho = r"H:\Materias - Escola\PYTHON\Atividade4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [26]:
arquivo_bruto = pd.read_excel(caminho, header=2)

In [27]:
arquivo_bruto

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...,...
5569,NaN,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0
5570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5571,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5573,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
arquivo_trabalhado = arquivo_bruto.iloc[0:5570, 1: ]
arquivo_trabalhado

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0

In [30]:
arquivo_trabalhado["DIFERENCA"] = arquivo_trabalhado["População Censo 2022"] - arquivo_trabalhado["População 2010 (Alterações de Limites até 2022)1"]

In [31]:
arquivo_trabalhado

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,DIFERENCA
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0,-2898.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0,6480.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0,-962.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0,8313.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0,-1139.0
...,...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0,2408.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0,1395.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0,-520.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0,670.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0,245222.0

In [34]:
arquivo_trabalhado.columns

Index(['UF', 'COD. UF', 'COD. MUNIC', 'NOME DO MUNICÍPIO',
       'População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022', 'DIFERENCA'],
      dtype='str')

In [45]:
estado = ( arquivo_trabalhado.groupby("UF")[["População Município 2010\n(Sinopse)",
       'População Censo 2022', 'DIFERENCA']]

        .sum()
        .reset_index()
       )

In [46]:
estado

    UF  População Município 2010\n(Sinopse)  População Censo 2022  DIFERENCA
0   AC                             733559.0              830018.0    96459.0
1   AL                            3120494.0             3127683.0     6796.0
2   AM                            3483985.0             3941613.0   457628.0
3   AP                             669526.0              733759.0    64233.0
4   BA                           14016906.0            14141626.0   124555.0
5   CE                            8452381.0             8794957.0   343313.0
6   DF                            2570160.0             2817381.0   245222.0
7   ES                            3514952.0             3833712.0   318760.0
8   GO                            6003788.0             7056495.0  1054706.0
9   MA                            6574789.0             6776699.0   201910.0
10  MG                           19597330.0            20539989.0   942659.0
11  MS                            2449024.0             2757013.0   307989.0
12  MT                            3035122.0             3658649.0   623527.0
13  PA                            7581051.0             8120131.0   539080.0
14  PB                            3766528.0             3974687.0   208159.0
15  PE                            8796448.0             9058931.0   262876.0
16  PI                            3118360.0             3271199.0   152102.0
17  PR                           10444526.0            11444380.0   999854.0
18  RJ                           15989929.0            16055174.0    65245.0
19  RN                            3168027.0             3302729.0   134702.0
20  RO                            1562409.0             1581196.0    18787.0
21  RR                             450479.0              636707.0   186228.0
22  RS                           10693929.0            10882965.0   189036.0
23  SC                            6248436.0             7610361.0  1361925.0
24  SE                            2068017.0             2210004.0   142152.0
25  SP                           41262199.0            44411238.0  3149039.0
26  TO                            1383445.0             1511460.0   128015.0